### ISSUE TITLE
website is broken https://tmdb.apps.quintero.io/

### ISSUE THREAD

**Issue by daniloab** [nerdsupremacist/tmdb#1]
when try to access the url https://tmdb.apps.quintero.io/ return error 502

![Screen Shot 2020-12-07 at 16 10 19](https://user-images.githubusercontent.com/19939822/101394083-ca053e80-38a6-11eb-9701-97f9b1c8951a.png)

**Comment by limk10** [comment]
when I send a POST to see the documentation it returns 502... heeeeelp

**Comment by nerdsupremacist** [comment]
Ah it crashed yesterday. Should be back up
