### ISSUE TITLE
Can you add a genre filter

### ISSUE THREAD

**Issue by YoussefRabeiii** [nerdsupremacist/tmdb#6]
i want to get like the top 10 comedy movies or series but i can't search by a field like genre

i thought i could use the where argument like in [contentful](https://www.contentful.com/) graphql api (i thought this was a graphql thing not that they made it) 

And You are doing great job with this api, i love it keep it up

And if you want to not do like one for genre and one for age and one for ....... try implement the where argument so we can search by fields 

Thanks again

**Comment by nerdsupremacist** [comment]
That's a great idea. I'll take a look. But I think I'll go about it in a slightly different way.

Right now Genres and Keywords are already objects types in the API.
We can make them conform to Node (so you can find with by their id). 
Add some discovery features to them like finding the listing the genres. 
And add a way to get from the genre to the movies or shows

**Comment by YoussefRabeiii** [comment]
And take a look at this repo
I started using it yesterday alongside your api
both of you  @nerdsupremacist @saeris are doing amazing work
I just have one problem right now, i need the episodes and i'm using @saeris api to get the series/movies and i'm using yours to get the specifics about this particular series/movie and i need the id to connect between them but your id format is a string and his is a integer and i kinda need it to be integer because i'm gonna add it to the URL so can you add like this id 

and right now i don't know why did i do this like this but i remember i had a good reason but right now i'm coding/playing with your APIs for the past 20 hours

**Comment by nerdsupremacist** [comment]
Hey so quick update! I just added a way to get movies and shows based on Genres (and Keywords, Production Company, and TV Network)

I also made all of them conform to `Node` so that APIs such as Relay can using refetching for pagination.
As for the IDs being strings, that is just so that they conform to `Node`.
You see, Relay and similar frameworks will require that every object has a unique ID. And the API from themoviedb.org does not have unique IDs across types.

Take for example the ID: MDoxMQ==
It's actually a base64 encoded string. If you decode it you get: 0:11
In this case the 0 means it's a movie. And the 11 is the integer id that you need.

But I think I can add a way to include the integer ID in the external ids object ;)

**Comment by nerdsupremacist** [comment]
Ok I managed to make that. So you can get the integer ID from `externalIds` (But only for People, Movies and TV Shows) Episodes, seasons, etc. are more complicated

**Comment by nerdsupremacist** [comment]
As for getting info from the genre take this example, which will get you the most popular Comedy movies:

```graphql
{
  node(id: "NTozNQ==") {
    ... on Genre {
      name
      movies {
        popular(first: 5) {
          edges {
            node {
              title
            }
          }
        }
      }
    }
  }
}
```

```json
{
  "data": {
    "node": {
      "movies": {
        "popular": {
          "edges": [
            {
              "node": {
                "title": "Cruella"
              }
            },
            {
              "node": {
                "title": "Nobody"
              }
            },
            {
              "node": {
                "title": "Monster Pets: A Hotel Transylvania Short"
              }
            },
            {
              "node": {
                "title": "Miraculous World: Shanghai – The Legend of Ladydragon"
              }
            },
            {
              "node": {
                "title": "22 vs. Earth"
              }
            }
          ]
        }
      },
      "name": "Comedy"
    }
  }
}
```

You can look up the genres using (warning all of these calls are using pagination):

```graphql
{
  genres {
    all(first: 5) {
      edges {
        node {
          name
        }
      }
    }
  }
}
```

**Comment by YoussefRabeiii** [comment]
WoW, your the best man, love how you did it and so quick i'm gonna play around with it now and gonna see what i will do 

thanks i will write you back if there is anything else

**Comment by YoussefRabeiii** [comment]
I love everything you did, i don't know if i should continue with my code from yesterday or should i start over but just before i start over i wouldn't need to start over if you could add getting a node by the external id (the tmdb one like 86831 insted of "Mjo4NjgzMQ==")
but this is an another issue so gonna create another issue

PS: Close the issue the says that your site is down #5
